### ISSUE TITLE
which files is it correct?

### ISSUE THREAD

**Issue by ghost** [munn33b/my-robotic-arm#1]
Please can you share how to start simulation? I mean which file is it correct to start this simulation?

**Comment by munn33b** [comment]
Hey @CansuAkdniz,
After you have downloaded the CoppeliaSim Simulation Software and done with the Environment Setup (as mentioned in Repo README, you can open Simulation File included in Simulation_files directory in CoppeliaSim and run Simulation. Make sure your ROS Master is running before you start CoppeliaSim.

**Comment by munn33b** [comment]
Feel free to Comment in case of any further Query, please close the issue in case you have resolved it.

**Comment by ghost** [comment]
Thank you for your answering. I solved it.
